package IDL_module.IDL_interfacePackage;


/**
* IDL_module/IDL_interfacePackage/ArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL_interface.idl
* Thursday, April 16, 2015 5:51:44 PM CDT
*/

public final class ArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public ArrayHolder ()
  {
  }

  public ArrayHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IDL_module.IDL_interfacePackage.ArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IDL_module.IDL_interfacePackage.ArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IDL_module.IDL_interfacePackage.ArrayHelper.type ();
  }

}
