package IDL_module;


/**
* IDL_module/IDL_interfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL_interface.idl
* Thursday, April 16, 2015 5:51:44 PM CDT
*/

public interface IDL_interfaceOperations 
{
  void shutdown ();
  int[][] sendMatrix (int[] data);
} // interface IDL_interfaceOperations
