package IDL_module;

/**
* IDL_module/IDL_interfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL_interface.idl
* Thursday, April 16, 2015 5:51:44 PM CDT
*/

public final class IDL_interfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public IDL_module.IDL_interface value = null;

  public IDL_interfaceHolder ()
  {
  }

  public IDL_interfaceHolder (IDL_module.IDL_interface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IDL_module.IDL_interfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IDL_module.IDL_interfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IDL_module.IDL_interfaceHelper.type ();
  }

}
